### ISSUE TITLE
Possible bug in \f conversion

### ISSUE THREAD

**Issue by neutrinog** [neutrinog/USFM-Tools#12]
We've ran into an issue where footnotes are not rendered correctly. 
For example here's a snippet from Acts 8:36-38

```
<note caller=\"+\" style=\"f\">
  <char style=\"ft\">Some ancient authorities add, in whole or in part, v. 37.</char>
  <char style=\"fqa\">And Philip said, \"If you believe with all your heart, you may be baptized.\" And the Ethiopian answered, I believe that Jesus Christ</char>
  is the Son of God.
</note>
```

You can see that `is the Son of God` is not inside of the `fqa` char.

We think this may be because the usfm source has this on a new line. See https://github.com/unfoldingWord/ulb-en/blob/master/44-ACT.usfm#L695

**Comment by kbuildsyourdotcom** [comment]
That is correct. The newline means the \fqa has ended. This is a problem with the source, not the conversion. \f has a start and end tag to denote the content boundaries, \fqa is a simpler tag that terminates at a newline character.

**Comment by neutrinog** [comment]
It looks like the spec says you have a footnote denoted by `\f ... \f*` and then you can mark different sections within that footnote e.g. `\f + \ft some stuff \fqa some more stuff \f*`

**Comment by neutrinog** [comment]
can you double check that?

**Comment by kbuildsyourdotcom** [comment]
You can denote section the /fqa inside the /f but the /fqa still ends at a like break as far as i can see in the spec. I'll take another look, but I'm pretty sure on this.

**Comment by neutrinog** [comment]
just noting for reference. This issue occurs anywhere there is a newline in the source. For example see https://github.com/unfoldingWord/ulb-en/blob/master/44-ACT.usfm#L670. I'm pretty sure they'll want the converter to be more forgiving in order to catch these, but I'll double check.

**Comment by neutrinog** [comment]
ok here's the news. They would like the convert to be more forgiving.
So...
If there is a new line in a suspicious location then you should ignore it, and return a warning that gives the location of the offending new line and and a statement that it was ignored.

I'm sure just what you were hoping for for. ;)
