### ISSUE TITLE
Add support for \qs

### ISSUE THREAD

**Issue by neutrinog** [neutrinog/USFM-Tools#13]
This was marked as fixed in https://github.com/Door43/USFM-Tools/commit/01632fe211d23a14597e425651c9cde4f9bc466f but it does not seem to support the correct end token: \qs* .

Could you double check this?

This is a high priority.

**Comment by kbuildsyourdotcom** [comment]
I believe this is now fixed and am closing this issue. Please confirm and open a new issue if there are problems. Thanks!
