### ISSUE TITLE
Add support for \rs

### ISSUE THREAD

**Issue by neutrinog** [neutrinog/USFM-Tools#9]
See Mark 16:8 for example.

**Comment by neutrinog** [comment]
https://door43.org/en/bible/notes/mrk/16/08

**Comment by kbuildsyourdotcom** [comment]
I don't see \rs anywhere in the USFM documentation.

**Comment by kbuildsyourdotcom** [comment]
I also don't see any USFM in the link you posted. Please let me know how to proceed :)

**Comment by neutrinog** [comment]
sorry I forgot you can't edit the pages.
This might be partly a bug. Possibly this should have been \sr. I'll let you know once I find out.

Here is the raw text:

```
ULB:

<usfm> \p \v 8 They went out and ran from the tomb; they were trembling and amazed. They said nothing to anyone because they were so afraid.

\rs Longer ending of Mark </usfm>
```

**Comment by kbuildsyourdotcom** [comment]
\sr is a section reference range like (21.17--24.22) so it's prob not that. Maybe \d, but even that I'm not sure of.

**Comment by neutrinog** [comment]
this is not a valid marker.
